server:
  http2.enabled: true
  compression:
    enabled: true
    min-response-size: 256

spring.data.mongodb:
  uri: ${MONGO_URI}

MONGO_URI: mongodb://fitness_service:fitness_password@localhost:27017/fitness_log?authSource=fitness_log