server:
  http2.enabled: true
  compression:
    enabled: true
    min-response-size: 256

spring.data.mongodb:
  uri: mongodb://fitness_service:fitness_password@localhost/fitness_log?authSource=fitness_log