server:
  http2.enabled: true
  compression:
    enabled: true
    min-response-size: 256
spring:
  data:
    mongodb:
      username: mongoadmin
      password: mongopassword
      database: fitness_log
      port: 27017
      host: mongodb