name: Dockare Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: openjdk:16-oracle

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: ./gradlew bootBuildImage
