name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Test ENV variables
      run: echo ${GITHUB_RUN_ID} && echo ${GITHUB_RUN_NUMBER} && echo ${GITHUB_JOB} && echo ${GITHUB_REPOSITORY}
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build the Docker Image using Buildpacks
      run: ./gradlew bootBuildImage
    - name: Retag Docker image
      run: docker image tag docker.io/library/fitness-backend:0.0.1-SNAPSHOT ${GITHUB_REPOSITORY}:b${GITHUB_RUN_NUMBER}-${GITHUB_SHA::8}
    
